# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waDeviceCapabilities/WAProtobufsDeviceCapabilities.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'waDeviceCapabilities/WAProtobufsDeviceCapabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8waDeviceCapabilities/WAProtobufsDeviceCapabilities.proto\x12\x1dWAProtobufsDeviceCapabilities\"\x96\x06\n\x12\x44\x65viceCapabilities\x12\x64\n\x14\x63hatLockSupportLevel\x18\x01 \x01(\x0e\x32\x46.WAProtobufsDeviceCapabilities.DeviceCapabilities.ChatLockSupportLevel\x12T\n\x0clidMigration\x18\x02 \x01(\x0b\x32>.WAProtobufsDeviceCapabilities.DeviceCapabilities.LIDMigration\x12^\n\x11\x62usinessBroadcast\x18\x03 \x01(\x0b\x32\x43.WAProtobufsDeviceCapabilities.DeviceCapabilities.BusinessBroadcast\x12V\n\ruserHasAvatar\x18\x04 \x01(\x0b\x32?.WAProtobufsDeviceCapabilities.DeviceCapabilities.UserHasAvatar\x12r\n\x1bmemberNameTagPrimarySupport\x18\x05 \x01(\x0e\x32M.WAProtobufsDeviceCapabilities.DeviceCapabilities.MemberNameTagPrimarySupport\x1a&\n\rUserHasAvatar\x12\x15\n\ruserHasAvatar\x18\x01 \x01(\x08\x1a.\n\x11\x42usinessBroadcast\x12\x19\n\x11importListEnabled\x18\x01 \x01(\x08\x1a\x30\n\x0cLIDMigration\x12 \n\x18\x63hatDbMigrationTimestamp\x18\x01 \x01(\x04\"U\n\x1bMemberNameTagPrimarySupport\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x14\n\x10RECEIVER_ENABLED\x10\x01\x12\x12\n\x0eSENDER_ENABLED\x10\x02\"7\n\x14\x43hatLockSupportLevel\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07MINIMAL\x10\x01\x12\x08\n\x04\x46ULL\x10\x02\x42\x30Z.go.mau.fi/whatsmeow/proto/waDeviceCapabilities')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waDeviceCapabilities.WAProtobufsDeviceCapabilities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.go.mau.fi/whatsmeow/proto/waDeviceCapabilities'
  _globals['_DEVICECAPABILITIES']._serialized_start=92
  _globals['_DEVICECAPABILITIES']._serialized_end=882
  _globals['_DEVICECAPABILITIES_USERHASAVATAR']._serialized_start=602
  _globals['_DEVICECAPABILITIES_USERHASAVATAR']._serialized_end=640
  _globals['_DEVICECAPABILITIES_BUSINESSBROADCAST']._serialized_start=642
  _globals['_DEVICECAPABILITIES_BUSINESSBROADCAST']._serialized_end=688
  _globals['_DEVICECAPABILITIES_LIDMIGRATION']._serialized_start=690
  _globals['_DEVICECAPABILITIES_LIDMIGRATION']._serialized_end=738
  _globals['_DEVICECAPABILITIES_MEMBERNAMETAGPRIMARYSUPPORT']._serialized_start=740
  _globals['_DEVICECAPABILITIES_MEMBERNAMETAGPRIMARYSUPPORT']._serialized_end=825
  _globals['_DEVICECAPABILITIES_CHATLOCKSUPPORTLEVEL']._serialized_start=827
  _globals['_DEVICECAPABILITIES_CHATLOCKSUPPORTLEVEL']._serialized_end=882
# @@protoc_insertion_point(module_scope)
